#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint-staged to lint and format code before commit
npx --no-install lint-staged || {
  echo "[1;31m❌ Commit rejected! Linting or formatting failed. Please fix the errors and try again.[0m"
  exit 1
}
